### ISSUE TITLE
'ObjectiveGit/ObjectiveGit.h' file not found

### ISSUE THREAD

**Issue by JimRoepcke** [Raekye/ObjectiveGit-iOS-Example#1]
I have the Objective-Git dependencies installed (brew, xctool, cmake).

I cloned this repo, git submodule update --init --recursive, cd objective-git; script/bootstrap.

I build, and I get this error:

/Users/jim/Projects/oss/github/Raekye/ObjectiveGit-iOS-Example/ObjectiveGit-iOS-Example/DetailViewController.m:10:9: 'ObjectiveGit/ObjectiveGit.h' file not found

line 10 is:
# import <ObjectiveGit/ObjectiveGit.h>

I've tried building this because I'm having the same problem in my project.

How do you get that import to work?

**Comment by JimRoepcke** [comment]
Not sure why, but later on this started to build fine.

But I was having problems in my own project, and that's because my project has non-standard build configuration names (ie: not Debug and Release).

Thanks for the example, it helped me along!

**Comment by Raekye** [comment]
I see, I was going to look at it this morning, but sounds like you already got it fixed. Glad the example helped though!
